export const DASHBOARD_CATEGORY = "DASHBOARD_CATEGORY";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_ADMIN = "LOGOUT_ADMIN";
export const GET_AUTH_USER = "GET_AUTH_USER";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const ADD_JOB_PROFILE = "ADD_JOB_PROFILE";

// DIRECTORY
export const GET_SEARCH_RESULT_DIRECTORY = "GET_SEARCH_RESULT_DIRECTORY";
export const GET_PROFILE = "GET_PROFILE";
export const CLOSE_MODAL = "CLOSE_MODAL";

// JOB
export const CREATE_JOB = "CREATE_JOB";
export const GET_JOB = "GET_JOB";
export const GET_JOB_LIST = "GET_JOB_LIST";
export const SEARCH_JOB_LIST = "SEARCH_JOB_LIST";
export const EDIT_JOB = "EDIT_JOB";
export const DELETE_JOB = "DELETE_JOB";
// EVENT
export const CREATE_EVENT = "CREATE_EVENT";
export const GET_EVENT = "GET_EVENT";
export const GET_EVENT_LIST = "GET_EVENT_LIST";
export const SEARCH_EVENT_LIST = "SEARCH_EVENT_LIST";
export const EDIT_EVENT = "EDIT_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";

// FORUM
export const CREATE_POST = "CREATE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const GET_POST_LIST = "GET_POST_LIST";
export const GET_POST_DETAILS = "GET_POST_DETAILS";

export const CREATE_COMMENT = "CREATE_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const GET_COMMENT = "GET_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
