const CountryData = [
  { name: "Afghanistan", dial_code: "+93", code: "AF" },
  { name: "Argentina", dial_code: "+54", code: "AR" },
  { name: "Bangladesh", dial_code: "+880", code: "BD" },
  { name: "Belgium", dial_code: "+32", code: "BE" },
  { name: "Brazil", dial_code: "+55", code: "BR" },
  { name: "Canada", dial_code: "+1", code: "CA" },
  { name: "China", dial_code: "+86", code: "CN" },
  { name: "Colombia", dial_code: "+57", code: "CO" },
  { name: "Denmark", dial_code: "+45", code: "DK" },
  { name: "France", dial_code: "+33", code: "FR" },
  { name: "India", dial_code: "+91", code: "IN" },
  { name: "Japan", dial_code: "+81", code: "JP" },
  { name: "Malaysia", dial_code: "+60", code: "MY" },
  { name: "Mexico", dial_code: "+52", code: "MX" },
  { name: "Nepal", dial_code: "+977", code: "NP" },
  { name: "Netherlands", dial_code: "+31", code: "NL" },
  { name: "New Zealand", dial_code: "+64", code: "NZ" },
  { name: "Pakistan", dial_code: "+92", code: "PK" },
  { name: "Portugal", dial_code: "+351", code: "PT" },
  { name: "Puerto Rico", dial_code: "+1 939", code: "PR" },
  { name: "Singapore", dial_code: "+65", code: "SG" },
  { name: "Spain", dial_code: "+34", code: "ES" },
  { name: "Sri Lanka", dial_code: "+94", code: "LK" },
  { name: "Swaziland", dial_code: "+268", code: "SZ" },
  { name: "Sweden", dial_code: "+46", code: "SE" },
  { name: "United Kingdom", dial_code: "+44", code: "GB" },
  { name: "United States", dial_code: "+1", code: "US" },
  { name: "Uruguay", dial_code: "+598", code: "UY" },
  { name: "Zimbabwe", dial_code: "+263", code: "ZW" },
  { name: "Hong Kong", dial_code: "+852", code: "HK" },
  { name: "Russia", dial_code: "+7", code: "RU" },
];

export default CountryData;
