import defaultImg from "../../../Assets/DirectoryList/default.png";

const data = [
  {
    id: 1,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/1",
  },
  {
    id: 2,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/2",
  },
  {
    id: 3,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/3",
  },
  {
    id: 4,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/4",
  },
  {
    id: 5,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/5",
  },
  {
    id: 6,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/6",
  },
  {
    id: 7,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/7",
  },
  {
    id: 8,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/8",
  },
  {
    id: 9,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/9",
  },
  {
    id: 10,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/10",
  },
  {
    id: 11,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/11",
  },
  {
    id: 12,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/12",
  },
  {
    id: 13,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/13",
  },
  {
    id: 14,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/14",
  },
  {
    id: 15,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/15",
  },
  {
    id: 16,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/16",
  },
  {
    id: 17,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/17",
  },
  {
    id: 18,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/18",
  },
  {
    id: 19,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/19",
  },
  {
    id: 20,
    name: "Mir Shahrukh Islam",
    series: "04",
    image: defaultImg,
    link: "/user/20",
  },
];

export default data;
